### Задание 1.

Импортируйте библиотеку **Numpy** и дайте ей псевдоним **np**.

In [1]:
import numpy as np

Создайте массив **Numpy** под названием **a** размером **5x2**, то есть состоящий из **5** строк и **2** столбцов. Первый столбец должен содержать числа **1, 2, 3, 3, 1**, а второй - числа **6, 8, 11, 10, 7**. Будем считать, что каждый столбец - это признак, а строка - наблюдение.

In [2]:
a = np.array([[ 1,  6],
              [ 2,  8],
              [ 3, 11],
              [ 3, 10],
              [ 1,  7]])

Затем найдите среднее значение по каждому признаку, используя метод **mean** массива **Numpy**. Результат запишите в массив **mean_a**, в нем должно быть 2 элемента.

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив **a_centered**, отняв от значений массива **а** средние значения соответствующих признаков, содержащиеся в массиве **mean_a**. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер **5x2**.

In [4]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3
Найдите скалярное произведение столбцов массива **a_centered**. В результате должна получиться величина **a_centered_sp**.

In [5]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

Затем поделите **a_centered_sp** на **N-1**, где **N** - число наблюдений.

In [6]:
N = np.size(a, 0)
a_centered_sp / (N - 1)

2.0

### Задание 4**
Число, которое мы получили в конце _задания 3_ является ковариацией двух признаков, содержащихся в массиве **а**. В _задании 3_ мы делили сумму произведений центрированных признаков на **N-1**, а не на **N**, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции **np.cov**. В качестве аргумента **m** функция **np.cov** должна принимать транспонированный массив **a**. В получившейся ковариационной матрице (массив **Numpy** размером **2x2**) искомое значение ковариации будет равно элементу в строке с индексом **0** и столбце с индексом **1**.

In [7]:
b = np.cov(a.T)
b[0, 1]

2.0

### Задание 5**
Создайте одномерный массив **z** случайных  целых чисел из равномерного распределения от **-50** до **50** включительно размерности **8**.

In [8]:
z = np.random.randint(-50, 51, 8)
z

array([ 41,  36, -49,  11, -30, -41,  24,  -7])

Найдите индексы положительных объектов.

In [9]:
np.where(z > 0)

(array([0, 1, 3, 6]),)

### Задание 6**
Создайте двумерный массив **X** случайных равномерно распределенных целых чисел от **0** до **255** включительно размерности **10** на **5**. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)

In [10]:
X = np.random.randint(0, 256, (10, 5))
X

array([[249, 252, 136, 125, 202],
       [106, 110, 174, 170, 146],
       [ 88, 132, 183,  83, 238],
       [ 70, 217,  26, 253,  92],
       [186, 173,  19,  70, 138],
       [238, 122, 200,  39, 168],
       [218,  87, 140, 243, 233],
       [248, 229, 147, 123,  11],
       [ 11, 118, 234, 106,  10],
       [235,  34, 219, 214,  39]])

Найдите среднее значение и стандартное отклонение по каждому признаку.

In [11]:
mean_feature = X.mean(axis=0)
mean_feature

array([164.9, 147.4, 147.8, 142.6, 127.7])

In [12]:
std_feature = X.std(axis=0)
std_feature

array([83.41156994, 65.38531945, 69.83953035, 70.5027659 , 82.13044502])

Вычислите массив **X_standard**, отняв от каждого признака среднее и поделив на стандартное отклонение.

In [13]:
X_standard = (X - mean_feature) / std_feature
X_standard

array([[ 1.00825341,  1.59974748, -0.16895875, -0.2496356 ,  0.90465844],
       [-0.70613705, -0.57199384,  0.37514571,  0.38863723,  0.22281628],
       [-0.92193445, -0.23552688,  0.50401255, -0.84535691,  1.34298554],
       [-1.13773185,  1.06445913, -1.74399798,  1.56589601, -0.43467438],
       [ 0.25296251,  0.3915252 , -1.84422775, -1.02974683,  0.12541025],
       [ 0.87637722, -0.38846641,  0.74742771, -1.4694459 ,  0.49068284],
       [ 0.63660233, -0.92375476, -0.1116846 ,  1.42405761,  1.28210677],
       [ 0.99626467,  1.24798656, -0.01145483, -0.27800328, -1.42091036],
       [-1.84506778, -0.44964222,  1.23425801, -0.51912857, -1.43308611],
       [ 0.84041099, -1.73433427,  1.01947994,  1.01272623, -1.07998928]])

Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице. Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [14]:
X_standard.mean(axis=0)

array([-6.66133815e-17, -1.11022302e-16, -1.33226763e-16,  8.88178420e-17,
        2.22044605e-17])

In [15]:
X_standard.std(axis=0)

array([1., 1., 1., 1., 1.])

### Задание 7**
Создайте два одномерных массива размерности **512** с любыми значениями. Будем считать, что каждый массив - это наблюдение с **512** признаками. 

In [16]:
a = np.random.randn(512)
b = np.random.randn(512)

In [17]:
a[:5]

array([-0.3633831 ,  1.40331388, -1.01708801, -0.30622095, -0.37174227])

In [18]:
b[:5]

array([ 0.71498325,  1.32861814,  0.58433713, -0.01455442,  0.53474397])

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.
Это получилась **L2-норма** (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)

In [19]:
d = a - b
d[:5]

array([-1.07836634,  0.07469574, -1.60142514, -0.29166653, -0.90648624])

In [20]:
np.sqrt((d**2).sum())

31.700018696435542

Посчитайте **L2 норму** для этих двух массивов с помощью _numpy.linalg_.

In [21]:
np.linalg.norm(a - b)

31.70001869643554

### Задание 8**
Используйте ранее созданный массив **X**. Найдите минимальное значение и максимальное по каждому признаку.

In [22]:
X.min(axis=0)

array([11, 34, 19, 39, 10])

In [23]:
X.max(axis=0)

array([249, 252, 234, 253, 238])

Вычислите массив **X_norm**, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.

In [24]:
X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_norm

array([[1.        , 1.        , 0.54418605, 0.40186916, 0.84210526],
       [0.39915966, 0.34862385, 0.72093023, 0.61214953, 0.59649123],
       [0.32352941, 0.44954128, 0.7627907 , 0.20560748, 1.        ],
       [0.24789916, 0.83944954, 0.03255814, 1.        , 0.35964912],
       [0.73529412, 0.63761468, 0.        , 0.14485981, 0.56140351],
       [0.95378151, 0.40366972, 0.84186047, 0.        , 0.69298246],
       [0.8697479 , 0.24311927, 0.5627907 , 0.95327103, 0.97807018],
       [0.99579832, 0.89449541, 0.59534884, 0.39252336, 0.00438596],
       [0.        , 0.3853211 , 1.        , 0.31308411, 0.        ],
       [0.94117647, 0.        , 0.93023256, 0.81775701, 0.12719298]])

Убедитесь, что теперь минимальное значение стало равно **0**, а максимальное - **1**.
Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)

In [25]:
X_norm.min(axis=0)

array([0., 0., 0., 0., 0.])

In [26]:
X_norm.max(axis=0)

array([1., 1., 1., 1., 1.])